[package]
name = "srfs-core"
version = "0.1.1"
edition = "2021"
description = "Simple Rust File System (Core)"
repository = "https://github.com/lasiotus/srfs-core"
keywords = ["filesystem", "no_std"]
categories = ["filesystem", "no-std"]
license = "MIT OR Apache-2.0"

[features]
default = []
std = []

[dependencies]
crc = "3.0"
log = "0.4.20"

[dev-dependencies]
rand = "0.8"
